/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ExtractorsRouteImport } from './routes/extractors'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TerminalsIndexRouteImport } from './routes/terminals/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as TerminalsTerminalIdRouteImport } from './routes/terminals/$terminalId'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as HistoryCommitsRouteImport } from './routes/history/commits'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractorsRoute = ExtractorsRouteImport.update({
  id: '/extractors',
  path: '/extractors',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalsIndexRoute = TerminalsIndexRouteImport.update({
  id: '/terminals/',
  path: '/terminals/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalsTerminalIdRoute = TerminalsTerminalIdRouteImport.update({
  id: '/terminals/$terminalId',
  path: '/terminals/$terminalId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryCommitsRoute = HistoryCommitsRouteImport.update({
  id: '/history/commits',
  path: '/history/commits',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/extractors': typeof ExtractorsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/history/commits': typeof HistoryCommitsRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/terminals/$terminalId': typeof TerminalsTerminalIdRoute
  '/sessions/': typeof SessionsIndexRoute
  '/terminals/': typeof TerminalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/extractors': typeof ExtractorsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/history/commits': typeof HistoryCommitsRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/terminals/$terminalId': typeof TerminalsTerminalIdRoute
  '/sessions': typeof SessionsIndexRoute
  '/terminals': typeof TerminalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/extractors': typeof ExtractorsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/history/commits': typeof HistoryCommitsRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/terminals/$terminalId': typeof TerminalsTerminalIdRoute
  '/sessions/': typeof SessionsIndexRoute
  '/terminals/': typeof TerminalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/extractors'
    | '/settings'
    | '/tasks'
    | '/history/commits'
    | '/sessions/$sessionId'
    | '/terminals/$terminalId'
    | '/sessions/'
    | '/terminals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/extractors'
    | '/settings'
    | '/tasks'
    | '/history/commits'
    | '/sessions/$sessionId'
    | '/terminals/$terminalId'
    | '/sessions'
    | '/terminals'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/extractors'
    | '/settings'
    | '/tasks'
    | '/history/commits'
    | '/sessions/$sessionId'
    | '/terminals/$terminalId'
    | '/sessions/'
    | '/terminals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExtractorsRoute: typeof ExtractorsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  HistoryCommitsRoute: typeof HistoryCommitsRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  TerminalsTerminalIdRoute: typeof TerminalsTerminalIdRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  TerminalsIndexRoute: typeof TerminalsIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extractors': {
      id: '/extractors'
      path: '/extractors'
      fullPath: '/extractors'
      preLoaderRoute: typeof ExtractorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminals/': {
      id: '/terminals/'
      path: '/terminals'
      fullPath: '/terminals/'
      preLoaderRoute: typeof TerminalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminals/$terminalId': {
      id: '/terminals/$terminalId'
      path: '/terminals/$terminalId'
      fullPath: '/terminals/$terminalId'
      preLoaderRoute: typeof TerminalsTerminalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/commits': {
      id: '/history/commits'
      path: '/history/commits'
      fullPath: '/history/commits'
      preLoaderRoute: typeof HistoryCommitsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExtractorsRoute: ExtractorsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  HistoryCommitsRoute: HistoryCommitsRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  TerminalsTerminalIdRoute: TerminalsTerminalIdRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  TerminalsIndexRoute: TerminalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
